"""tools.decisions — decision log + integrity check (STUB CONTRACT).

Owner: Dias Sarkytbaev (Phase 2, T2.1 / T2.2). Stub contract authored in Phase 0
(T0.8). Do NOT change signatures, constrained params, or return shapes without
agreement (CLAUDE.md §1).

`verify_graph_integrity` is the tool whose ERROR the loop branches on (Part B, B2;
TODO grading row "one tool error reaching the loop as its own branch"). It must
RETURN a structured error, never raise and never return a bad value dressed as
valid data.
"""

from __future__ import annotations

from typing import Literal


def append_decision_record(
    component: str,
    decision: str,
    rationale: str,
    status: Literal["proposed", "accepted", "superseded"],
) -> dict:
    """Append one decision record to the authored `decisions` layer of the graph.

    Append-only and recoverable -> ungated (CLAUDE.md §5). Writes to the AUTHORED
    layer, which no scan may overwrite; the record REFERENCES a component by id /
    symbol_uid, it is never stored inside a structural node (CLAUDE.md §6).

    Constrained params:
      component  required; the component / symbol_uid the decision is about.
      decision   required; what was decided.
      rationale  required; why — including the rejected alternative where relevant.
      status     enum: "proposed", "accepted", or "superseded".

    When NOT to call: do not use this to edit structural nodes/edges (that is
    derived data, regenerated by scans) — only to record an authored decision.

    Returns (contract): the stored record, e.g.
        {"component": <str>, "decision": <str>, "rationale": <str>,
         "status": <str>, "ts": <iso8601 str>}
    """
    raise NotImplementedError("Phase 2 (Dias): implement append_decision_record")


def verify_graph_integrity(
    scope: Literal["nodes", "edges", "all"],
) -> dict:
    """Run a domain integrity check over the graph. Returns a STRUCTURED error.

    Checks invariants such as: edges pointing at missing nodes (orphan edges),
    duplicate node ids, an empty scan result where source files clearly exist, and
    decisions whose symbol_uid no longer resolves (orphaned decisions — surfaced,
    not deleted; CLAUDE.md §6).

    Constrained param:
      scope  enum: "nodes", "edges", or "all".

    On failure this RETURNS (does not raise) a structured error so the loop can
    branch on it without the bad state ever re-entering context as valid data
    (Part B, B2):
        {"error": "graph_integrity_failed", "details": [<str>, ...]}
    On success:
        {"ok": True, "scope": <str>, "checked": <int>}
    """
    raise NotImplementedError("Phase 2 (Dias): implement verify_graph_integrity")
